version: '3.5'

services:
  db:
    restart: always
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres


networks:
  app_network:

volumes:
  db_data:

